---
title: Benefit News
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: hello@4benefitnews.com
description: A community around sharing news about companies that help build positive
  change in the world.
baseurl: ''
url: http://4benefitnews.com
twitter_username: 4benefitnews
facebook_page: 4benefitnews
pinterest_page: 4benefitnews
github_username: whosdustin
markdown: kramdown
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
